### PR TITLE
Add a test for non-validator (ordinary) node

### PR DESCRIPTION
**Pull request by phahulin**
Add node0 which is not a validator node (doesn't have engine signer set).
Add a `scripts/watchOrdinaryNode.js` that periodically fetches latest block info from the node and from the validator node1. Then it compares information about blocks (hashes and numbers). If there was connection error or hashes disagree or block numbers are too far apart, the script logs it into a separate file `parity-data/node0/check.log`.
At the end of the test suite, a new test checks if this file empty (so there were no errors).

At the current moment, the test actually fails for me, as there seem to be a brief difference in block hashes after epoch is changed.

### CODE REVIEW

**Comment by varasev** [comment]
Related to https://github.com/poanetwork/posdao-test-setup/issues/43.

**Comment by varasev** [comment]
> At the current moment, the test actually fails for me, as there seem to be a brief difference in block hashes after epoch is changed.

The reason can be that we launch two nodes for each of three validators. Maybe let's remove nodes 4, 5, 6 in the scope of this PR because anyway AuRa doesn't support running more than one node for a validator as we discovered a couple of months ago.

**Comment by phahulin** [comment]
I've removed nodes 4,5,6 and the error does not reproduce anymore.

**Comment by varasev** [comment]
Maybe change enumeration of the last three nodes from 7 8 9 to 4 5 6?

**Comment by phahulin** [comment]
Renumbered them

**Comment by varasev** [comment]
@vkomenda Please review this. Do you see any concerns here? I think we could merge it.

**Pull request merged**
